import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import collaborationImage from "../assets/research-collaboration.jpg";
import networkImage from "../assets/research-network.jpg";
import { members } from "../components/site/data";
import { PageHero, ResearchDiagram, Reveal, SectionHeading } from "../components/site/motion";

export const Route = createFileRoute("/ecosystem")({ head: () => ({ meta: [
  { title: "Ecosystem | JomoLab®" },
  { name: "description", content: "A Network of Extraordinary Minds building future-focused innovation through collaboration." },
  { property: "og:title", content: "Ecosystem | JomoLab®" },
  { property: "og:description", content: "Innovation Through Collaboration." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Ecosystem });

const reasons = [["Research Driven", "Every initiative begins with research, validation, and future forecasting."], ["Collaborative Innovation", "We bring together expertise across industries and geographies."], ["Future Focused", "Our work is designed around opportunities emerging over the next decade."], ["Sustainability First", "We believe innovation should create long-term value for people and the planet."], ["Global Perspective", "India, UAE, Europe, and beyond—our vision is borderless."]];

function Ecosystem() { return <>
  <PageHero label="Ecosystem" title={<><span className="block font-normal">R&amp;D</span><span className="block">Confederation</span></>} copy="A Network of Extraordinary Minds" />
  <section className="px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="R&D Confederation" title={<>A Network of Extraordinary<br className="hidden lg:block" /> Minds</>} /></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-12"><Reveal className="soft-panel p-8 md:p-12 lg:col-span-7"><p className="text-xl leading-[1.75] text-muted-foreground">JomoLab is an exclusive innovation confederation formed by entrepreneurs, scientists, researchers, technologists, advisors, and business leaders. Together, we identify future opportunities, conduct research, build products, and solve real-world challenges.</p><h2 className="mt-14 text-3xl font-normal">Why a Confederation?</h2><p className="mt-5 text-xl leading-[1.7] text-muted-foreground">Because the future cannot be built in silos. The most impactful innovations emerge when diverse expertise comes together under a shared vision.</p></Reveal><Reveal delay={100} className="image-panel min-h-96 lg:col-span-5"><img src={collaborationImage} alt="Interdisciplinary researchers working together" width={1600} height={1200} loading="lazy" /></Reveal></div></div></section>
  <section className="bg-muted px-5 py-20 md:px-8 md:py-28"><div className="site-container grid gap-4 lg:grid-cols-12"><Reveal className="image-panel min-h-96 lg:col-span-5"><img src={networkImage} alt="Connected research network" width={1600} height={1200} loading="lazy" /></Reveal><Reveal delay={100} className="blue-panel relative p-8 md:p-12 lg:col-span-7"><ResearchDiagram index={2} className="absolute -bottom-16 -right-12 size-72 text-primary/15" /><p className="section-label">Ratnesh Dwivedi</p><h2 className="text-3xl font-medium">Chief Thinker, JomoLab®</h2><p className="mt-4 text-muted-foreground">Serial Entrepreneur | TEDx Speaker | Growth Strategist</p><blockquote className="relative mt-14 max-w-2xl text-3xl font-light leading-snug">“Technology should not only make life smarter—it should make life better.</blockquote><p className="relative mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">JomoLab was founded with a vision to unite exceptional minds and create innovations that positively impact humanity. We are building an ecosystem where researchers, creators, entrepreneurs, and industry leaders collaborate to transform ambitious ideas into meaningful solutions. The future belongs to those who build it.</p></Reveal></div></section>
  <section className="px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="Confederation Members" title="Innovation Through Collaboration" /></Reveal><Reveal className="mt-10 max-w-4xl"><p className="text-xl leading-[1.7] text-muted-foreground">Our growing confederation consists of professionals and experts from technology, communication, research, business strategy, product development, and emerging industries.</p></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{members.map((name, index) => <Reveal key={name} delay={index * 60} className="research-card min-h-72 p-7"><ResearchDiagram index={index} className="absolute -right-10 -top-10 size-44 opacity-60" /><span className="number-chip">{String(index + 1).padStart(2, "0")}</span><h2 className="absolute bottom-8 left-7 right-7 text-2xl font-medium">{name}</h2></Reveal>)}</div><Reveal className="mt-10"><p className="text-xl">Along with a growing network of innovators worldwide Together, we are creating the foundation for future-focused innovation.</p></Reveal></div></section>
  <section className="bg-muted px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="" title="Why JomoLab?" /></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{reasons.map(([title, copy], index) => <Reveal key={title} delay={(index % 3) * 55} className={index === 1 ? "blue-panel p-8" : "soft-panel p-8"}><span className="number-chip">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-12 text-xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{copy}</p></Reveal>)}</div></div></section>
  <section className="px-5 py-20 md:px-8 md:py-28"><Reveal className="site-container grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="section-label">Join The Future</p><h2 className="section-title">Become Part of the JomoLab Confederation</h2></div><div className="lg:col-span-6 lg:col-start-7"><p className="text-xl leading-[1.7] text-muted-foreground">Whether you are an entrepreneur, researcher, scientist, investor, corporate leader, policymaker, or innovator, there is a place for you within the JomoLab ecosystem.</p><p className="mt-7 text-xl leading-[1.7]">Together, let&apos;s build technologies that create a better future for humanity.</p><Link to="/contact" className="story-link mt-10 pb-2 text-sm font-medium">Join Us <ArrowRight className="size-4" /></Link></div></Reveal></section>
  </>; }