import { createFileRoute } from "@tanstack/react-router";
import collaborationImage from "../assets/research-collaboration.jpg";
import networkImage from "../assets/research-network.jpg";
import { PageHero, ResearchDiagram, Reveal, SectionHeading } from "../components/site/motion";

export const Route = createFileRoute("/ecosystem")({ head: () => ({ meta: [
  { title: "Ecosystem & Ventures | JomoLab®" },
  { name: "description", content: "Explore the ventures and initiatives that turn JomoLab research into products, platforms, and global conversations." },
  { property: "og:title", content: "Ecosystem & Ventures | JomoLab®" },
  { property: "og:description", content: "A connected family of ventures turning ideas into impact." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Ecosystem });

function Ecosystem() { return <>
  <PageHero label="Page 3 / Ecosystem" title="R&D Confederation" copy="A Network of Extraordinary Minds" />
  <section className="px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="R&D Confederation" title="A Network of Extraordinary Minds" /></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-12"><Reveal className="soft-panel p-8 md:p-12 lg:col-span-7"><p className="text-xl leading-[1.75] text-muted-foreground">JomoLab is an exclusive innovation confederation formed by entrepreneurs, scientists, researchers, technologists, advisors, and business leaders. Together, we identify future opportunities, conduct research, build products, and solve real-world challenges.</p><h2 className="mt-14 text-3xl font-normal">Why a Confederation?</h2><p className="mt-5 text-xl leading-[1.7] text-muted-foreground">Because the future cannot be built in silos. The most impactful innovations emerge when diverse expertise comes together under a shared vision.</p></Reveal><Reveal delay={100} className="image-panel min-h-96 lg:col-span-5"><img src={collaborationImage} alt="Interdisciplinary researchers working together" width={1600} height={1200} loading="lazy" /></Reveal></div></div></section>
  <section className="bg-muted px-5 py-20 md:px-8 md:py-28"><div className="site-container grid gap-4 lg:grid-cols-12"><Reveal className="image-panel min-h-96 lg:col-span-5"><img src={networkImage} alt="Connected research network" width={1600} height={1200} loading="lazy" /></Reveal><Reveal delay={100} className="blue-panel relative p-8 md:p-12 lg:col-span-7"><ResearchDiagram index={2} className="absolute -bottom-16 -right-12 size-72 text-primary/15" /><p className="section-label">Ratnesh Dwivedi</p><h2 className="text-3xl font-medium">Chief Thinker, JomoLab®</h2><p className="mt-4 text-muted-foreground">Serial Entrepreneur | TEDx Speaker | Growth Strategist</p><blockquote className="relative mt-14 max-w-2xl text-3xl font-light leading-snug">“Technology should not only make life smarter—it should make life better.</blockquote><p className="relative mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">JomoLab was founded with a vision to unite exceptional minds and create innovations that positively impact humanity. We are building an ecosystem where researchers, creators, entrepreneurs, and industry leaders collaborate to transform ambitious ideas into meaningful solutions. The future belongs to those who build it.</p></Reveal></div></section>
  </>; }