import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import materialsLab from "../assets/future-materials-lab.jpg";
import { members } from "../components/site/data";
import { PageHero, ResearchDiagram, Reveal, SectionHeading } from "../components/site/motion";

export const Route = createFileRoute("/leadership")({ head: () => ({ meta: [
  { title: "Leadership, Advisors & Members | JomoLab®" },
  { name: "description", content: "Meet Chief Thinker Ratnesh Dwivedi, JomoLab's advisory board, and confederation members." },
  { property: "og:title", content: "Leadership, Advisors & Members | JomoLab®" },
  { property: "og:description", content: "Researchers, entrepreneurs, and industry leaders united by a shared vision for 2035." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Leadership });

const reasons = [["Research Driven", "Every initiative begins with research, validation, and future forecasting."], ["Collaborative Innovation", "We bring together expertise across industries and geographies."], ["Future Focused", "Our work is designed around opportunities emerging over the next decade."], ["Sustainability First", "We believe innovation should create long-term value for people and the planet."], ["Global Perspective", "India, UAE, Europe, and beyond—our vision is borderless."]];

function Leadership() { return <>
  <PageHero label="Page 3" title="Confederation Members" copy="Innovation Through Collaboration" />
  <section className="px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="Key Members" title="Innovation Through Collaboration" /></Reveal><Reveal className="mt-10 max-w-4xl"><p className="text-xl leading-[1.7] text-muted-foreground">Our growing confederation consists of professionals and experts from technology, communication, research, business strategy, product development, and emerging industries.</p></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{members.map((name, index) => <Reveal key={name} delay={index * 60} className="research-card min-h-72 p-7"><ResearchDiagram index={index} className="absolute -right-10 -top-10 size-44 opacity-60" /><span className="number-chip">{String(index + 1).padStart(2, "0")}</span><h2 className="absolute bottom-8 left-7 right-7 text-2xl font-medium">{name}</h2></Reveal>)}</div><Reveal className="mt-10"><p className="text-xl">Along with a growing network of innovators worldwide Together, we are creating the foundation for future-focused innovation.</p></Reveal></div></section>
  <section className="bg-muted px-5 py-20 md:px-8 md:py-28"><div className="site-container"><Reveal><SectionHeading eyebrow="Why JomoLab?" title="A different model for innovation" /></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{reasons.map(([title, copy], index) => <Reveal key={title} delay={(index % 3) * 55} className={index === 1 ? "blue-panel p-8" : "soft-panel p-8"}><span className="number-chip">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-12 text-xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{copy}</p></Reveal>)}<Reveal className="image-panel min-h-72"><img src={materialsLab} alt="Researcher examining future materials" width={1600} height={1200} loading="lazy" /></Reveal></div></div></section>
  <section className="px-5 py-20 md:px-8 md:py-28"><Reveal className="site-container grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="section-label">Join The Future</p><h2 className="section-title">Become Part of the JomoLab Confederation</h2></div><div className="lg:col-span-6 lg:col-start-7"><p className="text-xl leading-[1.7] text-muted-foreground">Whether you are an entrepreneur, researcher, scientist, investor, corporate leader, policymaker, or innovator, there is a place for you within the JomoLab ecosystem.</p><p className="mt-8 text-2xl font-medium">Together, let&apos;s build technologies that create a better future for humanity.</p><Link to="/contact" className="story-link mt-10 pb-2 font-medium text-primary">Join Us <ArrowRight className="size-4" /></Link></div></Reveal></section>
  </>; }