import { createFileRoute } from "@tanstack/react-router";
import { members } from "../components/site/data";
import { PageHero, Reveal } from "../components/site/motion";

export const Route = createFileRoute("/leadership")({ head: () => ({ meta: [
  { title: "Leadership, Advisors & Members | JomoLab®" },
  { name: "description", content: "Meet Chief Thinker Ratnesh Dwivedi, JomoLab's advisory board, and confederation members." },
  { property: "og:title", content: "Leadership, Advisors & Members | JomoLab®" },
  { property: "og:description", content: "Researchers, entrepreneurs, and industry leaders united by a shared vision for 2035." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Leadership });

const reasons = [["Research Driven", "Every initiative begins with research, validation, and future forecasting."], ["Collaborative Innovation", "We bring together expertise across industries and geographies."], ["Future Focused", "Our work is designed around opportunities emerging over the next decade."], ["Sustainability First", "We believe innovation should create long-term value for people and the planet."], ["Global Perspective", "India, UAE, Europe, and beyond—our vision is borderless."]];

function Leadership() { return <>
  <PageHero label="Page 3" title="Confederation Members" copy="Innovation Through Collaboration" />
  <section className="px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-screen-2xl"><Reveal><p className="max-w-4xl text-xl leading-[1.65] text-muted-foreground">Our growing confederation consists of professionals and experts from technology, communication, research, business strategy, product development, and emerging industries.</p><p className="section-label mt-14">Key Members</p></Reveal><div className="grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-4">{members.map((name, index) => <Reveal key={name} delay={index * 45} className="min-h-52 border-b border-r border-border bg-card p-6"><span className="font-mono text-xs text-primary">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-16 text-2xl font-medium">{name}</h2></Reveal>)}</div><Reveal className="mt-10"><p className="text-xl">Along with a growing network of innovators worldwide Together, we are creating the foundation for future-focused innovation.</p></Reveal></div></section>
  <section className="border-t border-foreground bg-wash px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-screen-2xl"><Reveal><h2 className="section-title">Why JomoLab?</h2></Reveal><div className="mt-12 grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-5">{reasons.map(([title, copy], index) => <Reveal key={title} delay={index * 40} className="min-h-64 border-b border-r border-border bg-background p-6"><span className="font-mono text-xs text-primary">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{copy}</p></Reveal>)}</div></div></section>
  <section className="border-t border-foreground px-5 py-20 md:px-8 md:py-24"><Reveal className="mx-auto grid max-w-screen-2xl gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="section-label">Join The Future</p><h2 className="section-title">Become Part of the JomoLab Confederation</h2></div><div className="lg:col-span-6 lg:col-start-7"><p className="text-xl leading-[1.65] text-muted-foreground">Whether you are an entrepreneur, researcher, scientist, investor, corporate leader, policymaker, or innovator, there is a place for you within the JomoLab ecosystem.</p><p className="mt-8 text-2xl font-medium">Together, let&apos;s build technologies that create a better future for humanity.</p><a href="/contact" className="story-link mt-10 inline-block pb-2 font-semibold text-primary">Join Us</a></div></Reveal></section>
</>; }