import { createFileRoute } from "@tanstack/react-router";
import { CtaBand } from "../components/site/CtaBand";
import { advisors, members } from "../components/site/data";
import { PageHero, ResearchDiagram, Reveal } from "../components/site/motion";

export const Route = createFileRoute("/leadership")({ head: () => ({ meta: [
  { title: "Leadership, Advisors & Members | JomoLab®" },
  { name: "description", content: "Meet Chief Thinker Ratnesh Dwivedi, JomoLab's advisory board, and confederation members." },
  { property: "og:title", content: "Leadership, Advisors & Members | JomoLab®" },
  { property: "og:description", content: "Researchers, entrepreneurs, and industry leaders united by a shared vision for 2035." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Leadership });

function Leadership() { return <>
  <PageHero label="04 / Confederation" title="Research is a collective practice." copy="Founders, researchers, technologists, and industry leaders bringing depth, scrutiny, and practical experience to JomoLab." />
  <section className="px-5 py-20 md:px-8 md:py-24"><Reveal className="mx-auto grid max-w-screen-2xl gap-10 lg:grid-cols-12"><div className="lg:col-span-3"><p className="section-label">Chief Thinker</p><div className="mt-10 hidden aspect-square max-w-48 border border-border p-6 lg:block"><ResearchDiagram index={2} /></div></div><div className="lg:col-span-8"><blockquote className="font-display text-[clamp(2.2rem,4vw,4.5rem)] font-light leading-[1.15]">“Technology should not only make life smarter—it should make life better.”</blockquote><div className="mt-10 border-t border-border pt-5"><p className="font-semibold">Ratnesh Dwivedi</p><p className="mt-1 font-mono text-[10px] uppercase text-muted-foreground">Chief Thinker / JomoLab®</p></div></div></Reveal></section>
  <section className="border-t border-foreground px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-screen-2xl"><Reveal className="grid gap-6 border-b border-border pb-9 lg:grid-cols-12"><div className="lg:col-span-5"><p className="section-label">Advisory board</p><h2 className="section-title">Guidance across disciplines.</h2></div><p className="max-w-xl leading-7 text-muted-foreground lg:col-span-5 lg:col-start-8">Advisors bring experience across media, technology, global programs, trade, and investment.</p></Reveal><div className="grid bg-border md:grid-cols-2 md:gap-px lg:grid-cols-4">{advisors.map(([name, role], index) => <Reveal key={name} delay={index * 50} className="research-card"><article className="flex min-h-72 flex-col p-7"><div className="flex items-start justify-between"><span className="font-mono text-[9px] text-primary">ADVISOR / 0{index + 1}</span><span className="font-mono text-[9px] text-muted-foreground">JML-ADV</span></div><h3 className="mt-16 font-display text-2xl font-medium">{name}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{role}</p><div className="mt-auto border-t border-border pt-4 font-mono text-[9px] uppercase text-muted-foreground">Strategic advisory</div></article></Reveal>)}</div></div></section>
  <section className="border-t border-foreground bg-wash px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-screen-2xl"><Reveal className="grid gap-6 lg:grid-cols-12"><div className="lg:col-span-5"><p className="section-label">Confederation members</p><h2 className="section-title">Many minds, one horizon.</h2></div><p className="max-w-xl leading-7 text-muted-foreground lg:col-span-5 lg:col-start-8">Specialist knowledge across international collaboration, space, growth, design, education, and immersive technology.</p></Reveal><div className="mt-12 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-4">{members.map(([name, role, location], index) => <Reveal key={name} delay={(index % 4) * 40} className="border-b border-r border-border bg-background"><article className="min-h-60 p-6"><span className="font-mono text-[9px] text-primary">MEMBER / {String(index + 1).padStart(2, "0")}</span><h3 className="mt-10 font-display text-xl font-medium">{name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{role}</p><p className="mt-6 font-mono text-[9px] uppercase text-muted-foreground">{location}</p></article></Reveal>)}</div><p className="mt-6 font-mono text-[10px] uppercase text-primary">The confederation continues to grow.</p></div></section>
  <CtaBand />
</>; }